//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentRegistration.Eligibility.WebCtrl {
    
    public partial class ShowStudentPhoto {
        protected System.Web.UI.HtmlControls.HtmlGenericControl DivPhoto;
        protected System.Web.UI.WebControls.Panel IWantThisVisible;
        protected System.Web.UI.WebControls.Image ImgPhoto;
        protected System.Web.UI.HtmlControls.HtmlGenericControl DivNoPhoto;
    }
}
