//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentRegistration.Eligibility.WebCtrl {
    
    public partial class StudentsAdvancedSearch {
        protected System.Web.UI.HtmlControls.HtmlGenericControl tblSelect;
        protected System.Web.UI.WebControls.Label lblCollegeType;
        protected System.Web.UI.WebControls.RadioButtonList rdbtnInstType;
        protected System.Web.UI.WebControls.Label lblCollegeName;
        protected System.Web.UI.WebControls.TextBox Inst_Name;
        protected System.Web.UI.WebControls.Label lblCollegeState;
        protected System.Web.UI.WebControls.DropDownList State_ID;
        protected System.Web.UI.WebControls.Label lblCollegeDistrict;
        protected System.Web.UI.WebControls.DropDownList District_ID;
        protected System.Web.UI.WebControls.Label lblCollegeTehsil;
        protected System.Web.UI.WebControls.DropDownList Tehsil_ID;
        protected System.Web.UI.WebControls.Label lblFaculty;
        protected System.Web.UI.WebControls.DropDownList ddlFaculty;
        protected System.Web.UI.WebControls.Label lblCourse;
        protected System.Web.UI.WebControls.DropDownList ddlCourse;
        protected System.Web.UI.WebControls.Label lblCrPart;
        protected System.Web.UI.WebControls.DropDownList ddlCoursePart;
        protected System.Web.UI.WebControls.TextBox txtDOB;
        protected System.Web.UI.HtmlControls.HtmlAnchor alinkCalender;
        protected System.Web.UI.WebControls.DropDownList ddlGender;
        protected System.Web.UI.WebControls.TextBox txtLastName;
        protected System.Web.UI.WebControls.TextBox txtFirstName;
        protected System.Web.UI.WebControls.Button btnSearch;
        protected System.Web.UI.HtmlControls.HtmlInputButton btnClear;
        protected System.Web.UI.WebControls.Label lblGridName;
        protected System.Web.UI.HtmlControls.HtmlGenericControl divDGNote;
        protected System.Web.UI.HtmlControls.HtmlTable tblDGElgRegular;
        protected System.Web.UI.WebControls.GridView dgElgRegular1;
        protected System.Web.UI.HtmlControls.HtmlTable tblDGRegPendingStudents;
        protected System.Web.UI.WebControls.GridView dgRegPendingStudents1;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidUniID;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidInstID;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidStateID;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidDistrictID;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidTehsilID;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidFacID;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidCrID;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidCr_MLrnPtrnID;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidCrPrID;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidElgFormNo;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidpkStudentID;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidCrMoLrnPtrnID;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidStep;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidpkYear;
        protected System.Web.UI.WebControls.Label lblUniversity;
        protected System.Web.UI.WebControls.Label lblCollege;
    }
}
