//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentRegistration.Eligibility {
    
    public partial class ELGV2_BulkProcess_reg_Students {
        protected System.Web.UI.WebControls.Label lblPageHead;
        protected StudentRegistration.Eligibility.searchInstNew SchInst1;
        protected System.Web.UI.WebControls.Label lblGridName;
        protected System.Web.UI.WebControls.DataGrid dgData;
        protected System.Web.UI.WebControls.Label lblData;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidInstID;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidUniID;
    }
}
