<%@ Page Language="C#" AutoEventWireup="true" MasterPageFile="~/Home.Master" CodeBehind="MatchingProfile.aspx.cs" Inherits="StudentRegistration.Eligibility.MatchingProfile" %>
<asp:Content ID="Content1" runat="server" ContentPlaceHolderID="ContentPlaceHolder1">
<style type="text/css">
.cssLbl
{
    color:#EE6340;
    font-weight:bold;
    font-size:10pt;
}
</style>
<script type="text/javascript">
function ClearControl()
{
    document.getElementById("<%=lblSubHeader.ClientID%>").innerText = '';
    document.getElementById("<%=txtPRN.ClientID%>").value = '';    
    document.getElementById("<%=txtOldPRN.ClientID%>").value = '';
    document.getElementById("<%=txtElgFrmNo.ClientID%>").value = '';
    document.getElementById("<%=chkLastName.ClientID%>").checked = false;
    document.getElementById("<%=chkFirstName.ClientID%>").checked = false;
    document.getElementById("<%=chkMiddleName.ClientID%>").checked = false;
    document.getElementById("<%=chkFatherLastName.ClientID%>").checked = false;
    document.getElementById("<%=chkFatherFistName.ClientID%>").checked = false;
    document.getElementById("<%=chkFatherMiddleName.ClientID%>").checked = false;
    document.getElementById("<%=chkMotherLastName.ClientID%>").checked = false;
    document.getElementById("<%=chkMotherFirstName.ClientID%>").checked = false;
    document.getElementById("<%=chkMotherMiddleName.ClientID%>").checked = false;
    document.getElementById("<%=chkTenth.ClientID%>").checked = false;
    document.getElementById("<%=chkTweelth.ClientID%>").checked = false;
}
   
function ShowAndHide()
{
    var auto = document.getElementById("<%=AutoGenerated.ClientID%>");
    var manual = document.getElementById("<%=ManualSearch.ClientID%>");
    var lbl = document.getElementById("<%=lblSmplSrch.ClientID%>");   
    var lblerror = document.getElementById("<%=lblErrorMsg.ClientID%>");    
    var note = document.getElementById("<%=divNote.ClientID%>")
    var Ainfo = document.getElementById("<%=AutoGeneratedInfo.ClientID%>");
    var Minfo = document.getElementById("<%=ManualInfo.ClientID%>")
    var MGrid = document.getElementById("<%=ManualSrchGrid.ClientID%>")
    var rpt = document.getElementById("<%=rpt.ClientID%>")
    var divMC = document.getElementById("<%=divMCriteria.ClientID%>")
    
    lblerror.style.display = "none"; 
    MGrid.style.display = "none";
     
    if(lbl.innerText != "(Change Filter Criteria)")
    {
        ClearControl();
    }
    
   if(manual.style.display == "none")
   {
        manual.style.display = "inline";
        manual.style.width = "100%";        
        note.style.display = "none";          
        auto.style.display = "none";
        Ainfo.style.display = "none";
        rpt.style.display = "none";        
        lbl.innerText = "(Match Profile Automatically)";        
    }
    else
    {
        manual.style.display = "none";
        Minfo.style.display = "none";
        divMC.style.display = "none";
        rpt.style.display = "inline";   
        auto.style.display = "inline"; 
        note.style.display = "inline";
        Ainfo.style.display = "inline";        
        lbl.innerText = "(Match Profile Manually)";        
    } 
}

function fnValidate(ctrlToValidate)
{
    var myArr = new Array();
    if (document.getElementById("<%=hidIsPRNValidationRequired.ClientID%>").value == "Y") 
    {
        if (document.getElementById("<%=txtPRN.ClientID%>").value == "" && document.getElementById("<%=txtOldPRN.ClientID%>").value == "" && document.getElementById("<%=txtElgFrmNo.ClientID%>").value == "") 
        {
            myArr[myArr.length] = new Array(document.getElementById("<%=txtPRN.ClientID%>"), "Empty", "Please enter <%=lblPRN.Text%> / Old <%=lblPRN.Text%> / Eligibility Form No.", "text");
        }
        else 
        {
            myArr[myArr.length] = new Array(document.getElementById("<%=txtPRN.ClientID%>"), "NumericOnly", "Enter valid <%=lblPRN.Text%>.", "text");
            myArr[myArr.length] = new Array(document.getElementById("<%=txtOldPRN.ClientID%>"), "NumericOnly", "Enter valid <%=Label2.Text%>.", "text");
            myArr[myArr.length] = new Array(document.getElementById("<%=txtElgFrmNo.ClientID%>"), "AlphaNumericOnly", "Enter valid Eligibility Form No.", "text");
        }
    }
    else if (document.getElementById("<%=txtPRN.ClientID%>").value == "" && document.getElementById("<%=txtOldPRN.ClientID%>").value == "" && document.getElementById("<%=txtElgFrmNo.ClientID%>").value == "") {
        myArr[myArr.length] = new Array(document.getElementById("<%=txtPRN.ClientID%>"), "Empty", "Please enter <%=lblPRN.Text%> / Old <%=lblPRN.Text%> / Eligibility Form No.", "text");
    }
    
    var ret = validateMe(myArr,50,ctrlToValidate);
    
    if(ret)
    {
	
       var iChkCount = 0;   
       if(document.getElementById("<%=chkLastName.ClientID%>").checked)
       {
            iChkCount ++;
       } 
       if(document.getElementById("<%=chkFirstName.ClientID%>").checked)
       {
           iChkCount ++;
       } 
       if(document.getElementById("<%=chkMiddleName.ClientID%>").checked)
       {
            iChkCount ++;
       } 
       if(document.getElementById("<%=chkFatherLastName.ClientID%>").checked)
       {
           iChkCount ++;
       } 
       if(document.getElementById("<%=chkFatherFistName.ClientID%>").checked)
       {
            iChkCount ++;
       } 
       if(document.getElementById("<%=chkFatherMiddleName.ClientID%>").checked)
       {
            iChkCount ++;
       } 
       if(document.getElementById("<%=chkMotherLastName.ClientID%>").checked)
       {
            iChkCount ++;
       } 
       if(document.getElementById("<%=chkMotherFirstName.ClientID%>").checked)
       {
            iChkCount ++;
       } 
       if(document.getElementById("<%=chkMotherMiddleName.ClientID%>").checked)
       {
           iChkCount ++;
       } 
       if(document.getElementById("<%=chkTenth.ClientID%>").checked)
       {
           iChkCount ++;
       } 
       if(document.getElementById("<%=chkTweelth.ClientID%>").checked)
       {
            iChkCount ++;
       }
       
       if(iChkCount >= 2)
       {
            return true;
       }
       else
       {
            showValidationSummary(ctrlToValidate,"Please select minimum 2 matching criteria");
            return false;
       } 
   }
   else
   {
        return ret;
   }
}

</script>
<div id="ControlHolder">   
    <div align="left" id="PageTitleHolder">           
        <asp:Label ID="lblPageHead" runat="server" Text="Match Profile" meta:resourcekey="lblPageHeadResource1" />&nbsp;
        <asp:Label ID="lblSubHeader" runat="server" meta:resourcekey="lblSubHeaderResource1"/>           
        <div id="StudentLinkHolder"> </div>
        <asp:Label ID="lbl" runat="server" Text=""></asp:Label>
    </div>
    
    <div align="right" style="WIDTH: 100%; padding:0px 6px 0px 6px;">
    <asp:Label ID="lblErrorMsg" runat="server" CssClass="errorNote" style="display:none" meta:resourcekey="lblErrorMsgResource1"/>
    </div> 
    <div id="divNote" runat="server"> 
     <div style="width: 100%; background-color: #FFFACD; border: solid 1px #c0c0c0; vertical-align: top;
                margin-bottom: 10px;">
                <div>
                    <table id="AutoGeneratedInfo" runat="server" width="100%" cellpadding="0">   <tr>
                            <td width="5%" Rowspan="4">
                                <asp:Image runat="server" ID="Image2" ImageUrl="../images/Info.jpg" /></td>
                            <td width="1%" valign="top">1.</td>
                             <td valign="top"  width="100%">
                              This module enables user to find out multiple profiles of student registered in this university using multiple criteria. It presents the matching profiles to user, and based on human decision it allows to merge these profiles into a single one or allows to completely deleting the redundant profiles. This shall be used very carefully and responsibly because once a profile is deleted or merged, then removed profile details will not be available anymore.</td>
                        </tr> 
                        <tr>
                            
                            <td width="1%" valign="top">2.</td>
                             <td valign="top">
                              Click on the alphabets to get matched profile list accordingly.</td>
                        </tr>                         
                        <tr> 
                        <td width="1%" valign="top">3.</td>                          
                            <td valign="top">
                              Maximum limit of comparing student profile is five.</td>
                        </tr> 
                        <tr> 
                        <td width="1%" valign="top">4.</td>                          
                            <td valign="top">
                              To match the students profile manually, click on 'Match Profile Manually'.</td>
                        </tr>                                            
                    </table>
                    <table id="ManualInfo" runat="server" width="100%" cellpadding="0" style="display:none">
                        <tr>
                            <td width="5%" Rowspan="2">
                                <asp:Image runat="server" ID="Image1" ImageUrl="../images/Info.jpg" /></td>
                                <td width="1%" valign="top">1.</td>
                            <td valign="top">
                                First record indicates the student for which you are matching the profiles.</td>
                        </tr>
                        <tr>
                        <td width="1%" valign="top">2.</td>                                 
                            <td valign="top">
                               Maximum limit of comparing student profile is five.</td>
                                
                        </tr>
                        <tr>
                        <td></td>
                        <td width="1%" valign="top">3.</td>                                 
                            <td valign="top">
                               To narrow down your search result, click on 'Change Filter Criteria'.</td>
                                
                        </tr>                           
                    </table>
                </div>
            </div> 
    <div id="divMCriteria" runat="server" style="display:none">
        <table style="width:100%;text-align:left;">
            <tr>
                <td style="width:114px;"><b>Matching Criteria: </b></td>
                <td id="Mcriteria" runat="server"></td>
            </tr>
        </table>
    </div>   
    </div>
    <div id="rpt" runat="server">
     
<asp:Label ID="lblcnt" runat="server" CssClass="cssLbl"></asp:Label>
<br /><b>Matching Criteria</b>: Student's Name, Mother's Name, Father's Name, Date of Birth, Gender.
<br />
<br />

        <center>
            <asp:Repeater ID="rptStudNameIntials" runat="server" OnItemCommand="rptStudNameIntials_ItemCommand">
            <ItemTemplate>                    
                <asp:LinkButton style="font-size:11pt" ID="lnkbtn" CssClass="NavLink" runat="server" CommandName="FilterName" CommandArgument='<%# Eval("StudentNameIntials") %>' Text='<%# Eval("StudentNameIntials") %>' meta:resourcekey="lnkbtnResource1" />                       
            </ItemTemplate>
            <SeparatorTemplate><span style="font-size:11pt">|</span>
            </SeparatorTemplate>
            </asp:Repeater>
        </center>
    </div>
                    <br />                                 
                <div style="CURSOR: pointer;padding:0px 0px 4px 0px;" class="clRight">
                    <asp:Label ID="lblSmplSrch" runat="server" CssClass="SimpleSearch" onClick="return ShowAndHide();" Text="(Match Profile Manually)" meta:resourcekey="lblSmplSrchResource1"></asp:Label>
                </div> 
                               
                <div id="AutoGenerated" runat="server">
                    <div id="divGridHead" runat="server"><b>List of Matched Profiles</b></div>
                    
                   <asp:GridView ID="gVsysDuplicate" runat="server" 
                    Width="100%" 
                    AutoGenerateColumns="False" 
                    AllowPaging ="True" 
                    PageSize ="25" 
                    CssClass="clGrid" 
                    OnRowCommand="gVsysDuplicate_RowCommand" 
                    OnPageIndexChanging="gVsysDuplicate_PageIndexChanging" meta:resourcekey="gVsysDuplicateResource1">
                    
                    <pagerstyle  verticalalign="Bottom" horizontalalign="Right"/> 
                    <HeaderStyle HorizontalAlign="Center" Width="650px" />
                    <Columns>                                              
                        <asp:TemplateField meta:resourcekey="TemplateFieldResource1">
                            <HeaderStyle Width="8%" CssClass="gridHeader" />
					        <ItemStyle Width="8%" HorizontalAlign="Center" CssClass="gridItem" />
                        <HeaderTemplate>Sr No.</HeaderTemplate>
                        <ItemTemplate>
                            <%# Container.DataItemIndex+1 %>
                        </ItemTemplate>
                        </asp:TemplateField>
                        <asp:BoundField HeaderText="Student Name" DataField="Student_Name" meta:resourcekey="BoundFieldResource1">
                            <ItemStyle Width="45%" CssClass="gridItem"/>
                            <HeaderStyle CssClass="gridHeader" Width="45%"/>
                        </asp:BoundField>
                        <asp:BoundField DataField="Date_Of_Birth" HeaderText="Date of Birth" meta:resourcekey="BoundFieldResource2">
                            <ItemStyle  HorizontalAlign="Center" Width="15%" CssClass="gridItem"/>
                            <HeaderStyle CssClass="gridHeader" Width="15%"/>
                        </asp:BoundField>
                        <asp:BoundField DataField="Profile_Matched_Count" HeaderText="Matched Profiles Count" meta:resourcekey="BoundFieldResource3">
                            <ItemStyle  HorizontalAlign="Center" CssClass="gridItem" Width="15%"/>
                            <HeaderStyle CssClass="gridHeader" Width="15%"/>
                        </asp:BoundField>
                        <asp:TemplateField meta:resourcekey="TemplateFieldResource2" >
				            <HeaderStyle Width="20%" CssClass="gridHeader" />
					        <ItemStyle Width="20%" HorizontalAlign="Center" ForeColor="Navy" CssClass="gridItem" />
                            <ItemTemplate>
                                <asp:LinkButton ID="lnkSelect" runat="server" CommandArgument='<%# Eval("Matching_Profile_ID") %>' CommandName="ViewDetails" meta:resourcekey="lnkSelectResource1" Text="Compare Profiles"></asp:LinkButton>
                            </ItemTemplate>
                        </asp:TemplateField>                  
                    </Columns>
                </asp:GridView>
                </div>
                
                
                <fieldset id="ManualSearch" runat="server" style="display:none;width:100%;"> 
                                   
                    <div id="SearchPRN" runat="server">
                     <div style="WIDTH: 100%; PADDING-TOP: 8px;">
                        <div align="right" class="clLeft" style="HEIGHT: 25px; PADDING-TOP: 12px; WIDTH: 140px;">
                            <b><asp:Label ID="lblPRN" runat="server" Text="PRN" meta:resourcekey="lblPRNResource1" ></asp:Label> : </b>
                        </div>
                        <div align="left" class="clLeft">
                           &nbsp;<asp:TextBox ID="txtPRN" runat="server" Width="230px" CssClass="redbox" MaxLength="16" TabIndex="1" meta:resourcekey="txtPRNResource1"></asp:TextBox>
                        </div>                     
                    </div>
                    <div style="WIDTH: 100%; PADDING-TOP: 8px; CLEAR: both;">
                        <div align="right" class="clLeft" style="HEIGHT: 25px; PADDING-TOP: 12px;WIDTH: 140px;">
                            <b><asp:Label ID="Label2" runat="server" Text="Old PRN" meta:resourcekey="Label2Resource1" ></asp:Label> : </b>
                        </div>
                        <div align="left" class="clLeft">
                            &nbsp;<asp:TextBox ID="txtOldPRN" runat="server" Width="230px" CssClass="redbox" MaxLength="16" TabIndex="2" meta:resourcekey="txtOldPRNResource1" ></asp:TextBox>
                        </div>
                    </div>
                    <div style="WIDTH: 100%; PADDING-TOP: 8px; CLEAR: both;">
                        <div align="right" class="clLeft" style="HEIGHT: 25px; PADDING-TOP: 12px;WIDTH: 140px;">
                            <b><asp:Label ID="Label1" runat="server" Text="Eligibility Form No" meta:resourcekey="Label1Resource1" ></asp:Label> : </b>
                        </div>
                        <div align="left" class="clLeft">
                            &nbsp;<asp:TextBox ID="txtElgFrmNo" runat="server" Width="230px" CssClass="redbox" MaxLength="25" TabIndex="3" meta:resourcekey="txtElgFrmNoResource1" ></asp:TextBox>
                        </div>
                    </div>                    
                    </div>
                    <div id="MatchingCriteria" runat="server">
                             <div style="WIDTH: 100%; CLEAR: both; PADDING-TOP: 15px;" align="center">
                                    <div align="right" style="WIDTH: 140px;PADDING-TOP: 4px;" class="clLeft">
                                        <b>Student Name : </b>
                                     </div>
                                    <div align="left" style="WIDTH: 150px;" class="clLeft">
                                        &nbsp;<asp:CheckBox ID="chkLastName" runat="server" Text="Last Name" meta:resourcekey="chkLastNameResource1" />                                  
                                    </div>                                    
                                    <div align="left" style="WIDTH: 150px;" class="clLeft">
                                        &nbsp;<asp:CheckBox ID="chkFirstName" runat="server" Text="First Name" meta:resourcekey="chkFirstNameResource1" />                                    
                                    </div>                                    
                                    <div align="left" style="WIDTH: 150px;" class="clLeft">
                                        &nbsp;<asp:CheckBox ID="chkMiddleName" runat="server" Text="Middle Name" meta:resourcekey="chkMiddleNameResource1" />                                       
                                    </div>
                                    
                              </div>
                              <div  style="WIDTH: 100%; CLEAR: both; PADDING-TOP: 5px;" align="center">
                                    <div align="right" style="WIDTH: 140px;PADDING-TOP: 4px" class="clLeft">
                                        <b>Father Name : </b></div>
                                    <div align="left" style="WIDTH: 150px;" class="clLeft">
                                        &nbsp;<asp:CheckBox ID="chkFatherLastName" runat="server" Text="Father Last Name" meta:resourcekey="chkFatherLastNameResource1" />                                 
                                    </div>                                     
                                    <div align="left" style="WIDTH: 150px;" class="clLeft">
                                        &nbsp;<asp:CheckBox ID="chkFatherFistName" runat="server" Text="Father First Name" meta:resourcekey="chkFatherFistNameResource1" />                                                                     
                                    </div>                                     
                                    <div align="left" style="WIDTH: 150px;" class="clLeft">
                                        &nbsp;<asp:CheckBox ID="chkFatherMiddleName" runat="server" Text="Father Middle Name" meta:resourcekey="chkFatherMiddleNameResource1" />                                     
                                    </div>                                    
                              </div>
                              <div style="WIDTH: 100%; CLEAR: both; PADDING-TOP: 5px;" align="center">
                                    <div align="right" style="WIDTH: 140px;PADDING-TOP: 4px" class="clLeft">
                                        <b>Mother Name : </b></div>
                                    <div align="left" style="WIDTH: 150px;" class="clLeft">
                                        &nbsp;<asp:CheckBox ID="chkMotherLastName" runat="server" Text="Mother Last Name" meta:resourcekey="chkMotherLastNameResource1" />                                 
                                    </div>                                     
                                    <div align="left" style="WIDTH: 150px;" class="clLeft">
                                        &nbsp;<asp:CheckBox ID="chkMotherFirstName" runat="server" Text="Mother First Name" meta:resourcekey="chkMotherFirstNameResource1" />                                                                       
                                    </div>                                     
                                    <div align="left" style="WIDTH: 150px;" class="clLeft">
                                        &nbsp;<asp:CheckBox ID="chkMotherMiddleName" runat="server" Text="Mother Middle Name" meta:resourcekey="chkMotherMiddleNameResource1" />                                       
                                    </div>                                    
                              </div>
                              <div style="WIDTH: 100%; CLEAR: both; PADDING-TOP: 5px;" align="center">
                                    <div align="right" style="WIDTH: 140px;PADDING-TOP: 4px" class="clLeft">
                                        <asp:Label ID="lbl10" runat="server" Font-Bold="true" Text="10th Details : " meta:resourcekey="lbl10Resource1"></asp:Label></div>
                                    <div align="left" style="WIDTH: 530px;" class="clLeft">
                                        &nbsp;<asp:CheckBox ID="chkTenth" runat="server" Text="10th (Board Type, Board State, Board, Passing Certificate, Examination Seat Number)" meta:resourcekey="chkTenthResource1" />                                 
                                    </div>                                     
                              </div>
                              <div style="WIDTH: 100%; CLEAR: both; PADDING-TOP: 5px;" align="center">
                                    <div align="right" style="WIDTH: 140px;PADDING-TOP: 4px" class="clLeft">
                                        <asp:Label ID="lbl12" runat="server" Font-Bold="true" Text="12th Details : " meta:resourcekey="lbl12Resource1"></asp:Label></div>
                                    <div align="left" style="WIDTH: 530px;" class="clLeft">
                                        &nbsp;<asp:CheckBox ID="chkTweelth" runat="server" Text="12th (Board Type, Board State, Board, Passing Certificate, Examination Seat Number)" meta:resourcekey="chkTweelthResource1" />                                  
                                    </div>                                     
                              </div>
                            <div align="center" style="WIDTH: 100%; CLEAR: both; PADDING-TOP: 8px" class="clButtonHolder">
                            <asp:Button ID="btnSrch" runat="server" Text="Search" OnClientClick="return fnValidate(this);" OnClick="btnSrch_Click" meta:resourcekey="btnSrchResource1"  />
                            </div>
                        </div>                                       
                </fieldset>               
            
    <%--Serach Result Grid--%> 
    <div id="ManualSrchGrid" runat="server" style="display:none">    
       <div id="gCaption" runat="server"></div>
       <asp:GridView ID="gVSearchDuplicate" runat="server" Width="100%" style="min-height:100px" AutoGenerateColumns="False"
           CssClass="clGrid" EmptyDataText="No Matching Proflie Found." 
           HorizontalAlign="Center" OnRowDataBound="gVSearchDuplicate_RowDataBound" CaptionAlign="Left" meta:resourcekey="gVSearchDuplicateResource1">                    
                    <HeaderStyle HorizontalAlign="Center" Width="650px" />
                    <Columns>                                              
                        <asp:TemplateField meta:resourcekey="TemplateFieldResource3">
                            <HeaderStyle Width="6%" CssClass="gridHeader" />
					        <ItemStyle Width="6%" HorizontalAlign="Center" CssClass="gridItem" />
                        <HeaderTemplate>Sr No.</HeaderTemplate>
                        <ItemTemplate>
                            <%# Container.DataItemIndex+1 %>
                        </ItemTemplate>
                        </asp:TemplateField>
                        <asp:BoundField HeaderText="Student Name" DataField="StudentName" meta:resourcekey="BoundFieldResource4">
                            <ItemStyle Width="27%" CssClass="gridItem"/>
                            <HeaderStyle CssClass="gridHeader" Width="27%"/>
                        </asp:BoundField>
                         <asp:BoundField HeaderText="Student's Father Name" DataField="FatherName" meta:resourcekey="BoundFieldResource5">
                            <ItemStyle Width="27%" CssClass="gridItem"/>
                            <HeaderStyle CssClass="gridHeader" Width="27%"/>
                        </asp:BoundField>
                         <asp:BoundField HeaderText="Student's Mother Name" DataField="MotherName" meta:resourcekey="BoundFieldResource6">
                            <ItemStyle Width="27%" CssClass="gridItem"/>
                            <HeaderStyle CssClass="gridHeader" Width="27%"/>
                        </asp:BoundField>
                        <asp:BoundField DataField="Date_Of_Birth" HeaderText="Date of Birth" meta:resourcekey="BoundFieldResource7">
                            <ItemStyle  HorizontalAlign="Center" Width="12%" CssClass="gridItem"/>
                            <HeaderStyle CssClass="gridHeader" Width="12%"/>
                        </asp:BoundField>                         
                        <asp:BoundField DataField="StudentIDs" meta:resourcekey="BoundFieldResource8">
                            <ItemStyle  CssClass="off" />
                            <HeaderStyle CssClass="off" />
                        </asp:BoundField>                             
                    </Columns>                   
           <EmptyDataRowStyle Font-Bold="True" HorizontalAlign="Center" VerticalAlign="Middle" />
                </asp:GridView>
               
        <div align="center" style="WIDTH: 650px; CLEAR: both; PADDING-TOP: 10px" class="clButtonHolder">
            <asp:Button ID="btnCompareProfile" runat="server" Text="Compare Profiles" OnClick="btnCompareProfile_Click" meta:resourcekey="btnCompareProfileResource1" />
        </div>
        <br />
    </div>        
</div>
<input type="hidden" runat="server" id="hid_Matching_Profile_ID" />
<input type="hidden" runat="server" id="hid_BaseStudentIDs" />
<input type="hidden" runat="server" id="hid_MatchingStudentIDs" />
<input type="hidden" runat="server" id="hid_MatchingCriteria" />
 <input id="hidIsPRNValidationRequired" type="hidden" name="hidIsPRNValidationRequired" runat="server"/>

</asp:Content>