//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentRegistration.Eligibility {
    
    public partial class SearchInstitute {
        protected System.Web.UI.HtmlControls.HtmlGenericControl tblSelect;
        protected System.Web.UI.WebControls.RadioButtonList RadioButtonList1;
        protected System.Web.UI.WebControls.TextBox Inst_Name;
        protected System.Web.UI.WebControls.DropDownList State_ID;
        protected System.Web.UI.WebControls.DropDownList District_ID;
        protected System.Web.UI.WebControls.DropDownList Tehsil_ID;
        protected System.Web.UI.WebControls.ImageButton ImageButton6;
        protected System.Web.UI.WebControls.ImageButton ImageButton5;
        protected System.Web.UI.WebControls.ImageButton ImageButton4;
        protected System.Web.UI.WebControls.ImageButton ImageButton3;
        protected System.Web.UI.WebControls.ImageButton ImageButton2;
        protected System.Web.UI.WebControls.ImageButton ImageButton1;
    }
}
