//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentRegistration.Eligibility {
    
    public partial class StudentStatus {
        protected System.Web.UI.HtmlControls.HtmlForm Form1;
        protected UniversityPortal.InnerHeader TopLink1;
        protected System.Web.UI.WebControls.Label lblTitle;
        protected System.Web.UI.WebControls.Label lblInstName;
        protected System.Web.UI.HtmlControls.HtmlTableCell TDLink;
        protected UniversityPortal.SideLinks MainLink1;
        protected System.Web.UI.WebControls.LinkButton lnkSimpleSearch;
        protected System.Web.UI.WebControls.LinkButton lnkAdvSearch;
        protected System.Web.UI.HtmlControls.HtmlGenericControl divSimpleSearch;
        protected System.Web.UI.WebControls.TextBox txtPRN;
        protected System.Web.UI.WebControls.TextBox txtElgFormNo;
        protected System.Web.UI.WebControls.Button btnSimpleSearch;
        protected System.Web.UI.WebControls.Label lblMsg;
        protected System.Web.UI.HtmlControls.HtmlGenericControl divAdvSearch;
        protected StudentRegistration.Eligibility.WebCtrl.StudentsStatusSearch StudentsStatusSearch1;
        protected UniversityPortal.Footer Footer1;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidpkStudentID;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidpkYear;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidElgFormNo;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidSearchType;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidPRN;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidInstID;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidUniID;
    }
}
