//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentRegistration.Eligibility {
    
    public partial class BulkInsertForUniversity {
        protected System.Web.UI.HtmlControls.HtmlForm Form1;
        protected UniversityPortal.InnerHeader TopLink1;
        protected System.Web.UI.WebControls.Label lblTitle;
        protected System.Web.UI.HtmlControls.HtmlTableCell TDLink;
        protected UniversityPortal.SideLinks MainLink1;
        protected System.Web.UI.WebControls.Label lblSave;
        protected System.Web.UI.WebControls.DropDownList DD_Inst;
        protected System.Web.UI.WebControls.DropDownList DD_Course;
        protected System.Web.UI.WebControls.Button btnProcessData;
        protected System.Web.UI.WebControls.Label lblGrid;
        protected System.Web.UI.HtmlControls.HtmlTable tblGrid;
    }
}
