//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentRegistration.Eligibility {
    
    public partial class BulkInsertForCollege {
        protected System.Web.UI.HtmlControls.HtmlForm Form1;
        protected UniversityPortal.InnerHeader TopLink1;
        protected System.Web.UI.WebControls.Label lblTitle;
        protected System.Web.UI.WebControls.Label lblInstName;
        protected System.Web.UI.HtmlControls.HtmlTable tblLink;
        protected System.Web.UI.WebControls.LinkButton lnkSelectCr;
        protected System.Web.UI.WebControls.LinkButton lnkPRN;
        protected System.Web.UI.HtmlControls.HtmlTableCell TDLink;
        protected UniversityPortal.SideLinks MainLink1;
        protected System.Web.UI.HtmlControls.HtmlTable tblToolBarMain;
        protected System.Web.UI.HtmlControls.HtmlTable tblToolBar;
        protected System.Web.UI.WebControls.Button btnNew;
        protected System.Web.UI.WebControls.Button btnSave;
        protected System.Web.UI.WebControls.Button btnDelete;
        protected System.Web.UI.HtmlControls.HtmlTable tblUserControl;
        protected System.Web.UI.HtmlControls.HtmlTable tblMainTable;
        protected System.Web.UI.WebControls.Label lblSave;
        protected System.Web.UI.HtmlControls.HtmlTableRow trCourse;
        protected System.Web.UI.WebControls.DropDownList DD_Course;
        protected System.Web.UI.WebControls.DropDownList DD_CoursePart;
        protected System.Web.UI.WebControls.Button btnProcessData;
        protected System.Web.UI.WebControls.Label lblRights;
        protected System.Web.UI.HtmlControls.HtmlTableRow trStatistics;
        protected System.Web.UI.WebControls.Label lblStatistics;
        protected System.Web.UI.HtmlControls.HtmlTable tblStatistics;
        protected System.Web.UI.WebControls.Label lblUniCount;
        protected System.Web.UI.WebControls.Label lblNonPaidUniCount;
        protected System.Web.UI.WebControls.Label lblCollCount;
        protected System.Web.UI.WebControls.Label lblNonPaidCollCount;
        protected System.Web.UI.WebControls.Label lblNoRecords;
        protected System.Web.UI.WebControls.Label lblInfoNote;
        protected System.Web.UI.HtmlControls.HtmlTableRow trGrids;
        protected System.Web.UI.HtmlControls.HtmlTableRow trGridHeader;
        protected System.Web.UI.WebControls.Label lblUniCollPrn;
        protected System.Web.UI.WebControls.Label lblUnselectCheck;
        protected System.Web.UI.WebControls.DataGrid DG_University;
        protected System.Web.UI.WebControls.Label lblCollege;
        protected System.Web.UI.WebControls.Label lblDisplayNote;
        protected System.Web.UI.WebControls.DataGrid DG_College;
        protected System.Web.UI.WebControls.Label lblPRN;
        protected System.Web.UI.WebControls.DataGrid DG_PRN;
        protected UniversityPortal.Footer Footer1;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidInstID;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidUniID;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hid_Year;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidStudentID;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidCrMoLrnPtrnID;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidCrID;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidCrPrID;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidYear;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidCollege_Eligibility_Flag;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidRightsFlag;
    }
}
