//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentRegistration.Eligibility {
    
    public partial class ElgResolve_Inst_Student_Search {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected UniversityPortal.InnerHeader TopLink1;
        protected System.Web.UI.WebControls.Label lblTitle;
        protected System.Web.UI.WebControls.Label lblInstName;
        protected System.Web.UI.HtmlControls.HtmlTableCell TDLink;
        protected UniversityPortal.SideLinks MainLink1;
        protected StudentRegistration.Eligibility.schInst SchInst1;
        protected System.Web.UI.WebControls.Label lblGridName;
        protected System.Web.UI.WebControls.DataGrid dgData;
        protected System.Web.UI.WebControls.Label lblData;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidInstID;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidUniID;
        protected UniversityPortal.Footer Footer1;
    }
}
