//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Digital_College {
    
    public partial class Search_Control {
        protected System.Web.UI.WebControls.Label msgLabel;
        protected System.Web.UI.WebControls.TextBox PRN_No;
        protected System.Web.UI.HtmlControls.HtmlTableRow tr_AdvanceSearch1;
        protected System.Web.UI.WebControls.DropDownList DD_Course;
        protected System.Web.UI.WebControls.TextBox DOB;
        protected System.Web.UI.HtmlControls.HtmlTableRow tr_AdvanceSearch2;
        protected System.Web.UI.WebControls.TextBox LastName;
        protected System.Web.UI.WebControls.TextBox FirstName;
        protected System.Web.UI.HtmlControls.HtmlTableRow tr_AdvanceSearch3;
        protected System.Web.UI.WebControls.DropDownList Gender;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hid_pk_Student_ID;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hid_FormNo;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hid_Status;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hid_pk_CrPr_ID;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hid_pk_CrMoLrnPtrn_ID;
    }
}
